# Fuzzel Configuration
# Save to ~/.config/fuzzel/fuzzel.ini

[main]
font=JetBrainsMono Nerd Font:size=12
prompt="❯ "
icon-theme=Adwaita
fields=filename,name,generic,exec,categories,keywords
terminal=kitty
lines=4
width=35
horizontal-pad=20
vertical-pad=14
inner-pad=10
line-height=20
letter-spacing=0
layer=overlay
exit-on-keyboard-focus-loss=yes

[colors]
# Syntax: RRGGBBAA (Hex + Alpha transparency)
# 0x18181bef = Dark background (~90% opacity)
# 0x75f1faff = Accent highlight color

background=18181be6
text=ffffffff
match=75f1faff
selection=27272eff
selection-text=75f1faff
selection-match=75f1faff
border=3f3f46ff

[border]
width=2
radius=5

[dmenu]
mode=text
